# Generated by Django 2.1 on 2020-08-21 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('userID1', models.ManyToManyField(blank=True, related_name='userID1', to=settings.AUTH_USER_MODEL)),
                ('userID2', models.ManyToManyField(blank=True, related_name='userID2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('webpage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minFare', models.DecimalField(decimal_places=2, max_digits=2)),
                ('pricePerKm', models.DecimalField(decimal_places=2, max_digits=2)),
                ('company', models.ManyToManyField(blank=True, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=2)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=2)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateField()),
                ('content', models.CharField(max_length=200)),
                ('chat', models.ManyToManyField(blank=True, to='api.Chat')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('employeeNeed', models.CharField(max_length=25)),
                ('chargeAmount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=2)),
                ('paymentDate', models.DateField()),
                ('fare', models.ManyToManyField(to='api.Fare')),
            ],
        ),
        migrations.CreateModel(
            name='Permits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_modify', models.CharField(max_length=200)),
                ('p_create', models.CharField(max_length=200)),
                ('p_delete', models.CharField(max_length=200)),
                ('p_read', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('employee', models.ManyToManyField(blank=True, to='api.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeScore', models.DecimalField(decimal_places=2, max_digits=2)),
                ('clientScore', models.DecimalField(decimal_places=2, max_digits=2)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('startDate', models.DateField()),
                ('isReservation', models.BooleanField()),
                ('state', models.BooleanField()),
                ('client', models.ManyToManyField(to='api.Client')),
                ('driver', models.ManyToManyField(to='api.Driver')),
                ('endLocation', models.ManyToManyField(related_name='endLocation', to='api.Location')),
                ('payment', models.ManyToManyField(to='api.Payment')),
                ('startLocation', models.ManyToManyField(related_name='startLocation', to='api.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('atendido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chat', models.ManyToManyField(blank=True, to='api.Chat')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('carPlate', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='typeService',
            field=models.ManyToManyField(to='api.TypeService'),
        ),
        migrations.AddField(
            model_name='permits',
            name='role',
            field=models.ManyToManyField(blank=True, to='api.Role'),
        ),
        migrations.AddField(
            model_name='permits',
            name='screen',
            field=models.ManyToManyField(blank=True, to='api.Screen'),
        ),
        migrations.AddField(
            model_name='fare',
            name='typeService',
            field=models.ManyToManyField(blank=True, to='api.TypeService'),
        ),
        migrations.AddField(
            model_name='driver',
            name='currentVehicle',
            field=models.ManyToManyField(to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='details',
            name='service',
            field=models.ManyToManyField(to='api.Service'),
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
